abvis/urls.py
from django.conf.urls import url
from apps.dashboard.views import  event_csv, event_pdf
from apps.notification.views import notifications
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include


from apps.core.views import frontpage, signup


urlpatterns = [
    path('', frontpage, name='frontpage'),
   
    path('event_csv', event_csv, name='event_csv'),
    path('event_pdf', event_pdf, name='event_pdf'),
    path('app/', include('apps.dashboard.urls')),
    path('signup/', signup, name='signup'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('admindashboard/', include('apps.userprofile.urls')),
    path('notifications/', include('apps.notification.urls')),
    path('events/', include('apps.dashboard.urls')),
    path('', include('apps.core.urls')),
    path('family/',include('apps.userprofile.urls')),
    path('area/',include('apps.userprofile.urls')),
    path('event/',include('apps.userprofile.urls')),
    
]

apps/dashboard/urls.py
from django import views
from django.urls import path, include
from django.conf.urls import url

from .api import api_search
from .views import  add_event, dashboard, event_detail, apply_for_event,search,edit_event,event_csv


urlpatterns = [
    
    path('api/search/', api_search, name='api_search'),
    path('search/', search, name='search'),
    path('', dashboard, name='dashboard'),
    path('add/', add_event, name='add_event'),
    #path('event_csv', event_csv, name='event_csv'),
    path('<int:event_id>/', event_detail, name='event_detail'),
    path('<int:event_id>/edit/', edit_event, name='edit_event'),
    path('<int:event_id>/apply_for_event/', apply_for_event, name='apply_for_event'),
]

 

 

apps/dashboard/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Event(models.Model):

    ACTIVE = 'active'
    BOOKED = 'booked'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (BOOKED, 'Booked'),
        (ARCHIVED, 'Archived')
    )


    title = models.CharField(max_length=255)
    short_description = models.TextField()
    long_description = models.TextField(blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    volunteer_area = models.CharField(max_length=255, null=True)

  

    created_by = models.ForeignKey(User, related_name='events', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ACTIVE)

    def __str__(self):
        return self.title

class Application(models.Model):
    event = models.ForeignKey(Event, related_name='applications', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()

    created_by = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

apps/dashboard/forms.py
from django import forms

from .models import Event, Application

class AddEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields =['title', 'short_description', 'long_description', 'start_time', 'end_time','volunteer_area']

    

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = [ 'content', 'experience']

   
        

apps/dashboard/views.py
from apps.dashboard.forms import AddEventForm
from apps.dashboard.models import Application, Event
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseRedirect


from django.contrib.auth.decorators import login_required
from .forms import AddEventForm, ApplicationForm
from django.http import HttpResponse
from apps.notification.utilities import create_notification
import csv

# Import PDF Stuff
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

#Import Calendar Stuff


from .models import *


# Generate a PDF File Venue List
@login_required
def event_pdf(request):
	# Create Bytestream buffer
	buf = io.BytesIO()
	# Create a canvas
	c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
	# Create a text object
	textob = c.beginText()
	textob.setTextOrigin(inch, inch)
	textob.setFont("Helvetica", 14)
	
	# Designate The Model
	events = Event.objects.all()

	# Create blank list
	lines = []

	for event in events:
            lines.append(event.title)
            lines.append(event.short_description)
            lines.append(event.long_description)
            #lines.append(event.start_time)
            #lines.append(event.end_time)
            lines.append(event.volunteer_area)

            lines.append("=================================================================")
    # Loop
	for line in lines:
            textob.textLine(line)

	# Finish Up
	c.drawText(textob)
	c.showPage()
	c.save()
	buf.seek(0)

	# Return something
	return FileResponse(buf, as_attachment=True, filename='event.pdf')

#Generate Csv File event list
@login_required
def event_csv(request):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename=event.csv'
	
        # Create a csv writer
        writer = csv.writer(response)

        # Designate The Model
        events = Event.objects.all()

        # Add column headings to the csv file
        writer.writerow(['Event Title', 'Short Description', 'Long Description','Start Time', 'End Time', 'Volunteer Area'])

        # Loop Thu and output
        for event in events:
                writer.writerow([event.title, event.short_description, event.long_description, event.start_time, event.end_time, event.volunteer_area])

        return response




@login_required
def search(request):
    return render(request, 'dashboard/search.html')



@login_required
def dashboard(request):
    events = Event.objects.filter(status=Event.ACTIVE).order_by('-created_at')[0:9]

    return render(request, 'dashboard/dashboard.html' , {'events': events})


def event_detail(request, event_id):
    event = Event.objects.get(pk=event_id)

    return render(request, 'dashboard/event_detail.html', {'event': event})

@login_required
def apply_for_event(request, event_id):
    event = Event.objects.get(pk=event_id)

    if request.method == 'POST':
        form = ApplicationForm(request.POST)

        if form.is_valid():
            application = form.save(commit=False)
            application.event = event
            application.created_by = request.user
            application.save()

            create_notification(request, event.created_by, 'application', extra_id=application.id)

            

            return redirect('admindashboard')
    else:
        form = ApplicationForm()

    return render(request, 'dashboard/apply_for_event.html',{'form': form, 'event': event})

@login_required
def add_event(request):
    if request.method == 'POST':
        form = AddEventForm(request.POST)

        if form.is_valid():
            event = form.save(commit=False)
            event.created_by = request.user
            event.save()

            return redirect('admindashboard')
    else:
        form = AddEventForm()

    return render(request, 'dashboard/add_event.html',{'form': form})


@login_required
def edit_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id, created_by=request.user)

    if request.method == 'POST':
        form = AddEventForm(request.POST, instance=event)

        if form.is_valid():
            event = form.save(commit=False)
            event.status = request.POST.get('status')
            event.save()

            return redirect('admindashboard')
    else:
        form = AddEventForm(instance=event)

    return render(request, 'dashboard/edit_event.html', {'form': form, 'event': event})

apps/dashboard/templates/dashboard/add_event.html
{% extends 'core/base.html' %} 

{% block content %} 
    <div id="add-event-app">
    <h1 class="title"> Add Event</h1>

    <form v-on:submit="validateForm()" method="post" action="." >

        {% csrf_token %}

        {% if form.errors %} 
            {% for error in form.errors %} 
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="notifiation is-danger" v-if="errors.length">
            <p v-for="error in errors">
                [[ error ]]
            </p>

        </div>

        <div class="field">
            <lable> Title </lable>
            
            <div class="control">
                <input class="input" type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>
        
        <div class="field">
            <lable>Short description</lable>
            
            <div class="control">
                <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description"></textarea>
            </div>
        </div>

        <div class="field">
            <lable>Long description</lable>
            
            <div class="control">
                <textarea class="textarea" name="long_description" id="id_long_description" v-model="long_description"></textarea>
            </div>
        </div>

        <div class="field">
            <lable>Start Time (Hint: 1PM is 13:00)</lable>
            
            <div class="control">
                <input type="datetime" name="start_time" id="id_start_time" placeholder="MM/DD/YYYY HH:MM" v-model="start_time">
            </div>
        </div>

        <div class="field">
            <lable>End Time (Hint: 1PM is 13:00)</lable>
            
            <div class="control">
                <input type="datetime" name="end_time" id="id_end_time" placeholder="MM/DD/YYYY HH:MM" v-model="end_time">
            </div>
        </div>

        <div class="field">
            <lable> Volunteer Area </lable>
            
            <div class="control">
                <input class="input" type="text" name="volunteer_area" id="id_volunteer_area" v-model="volunteer_area">
            </div>
        </div>

        


        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>

    </form>

</div>

 

{% endblock %} 

{% block scripts %}
<script>
    const AddEventApp= {
        data() {
            return {
                title: '',
                short_description: '',
                long_description: '',
                start_time: '',
                end_time: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = [] 

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                
                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                
                if (this.long_description === '') {
                    this.errors.push('The long description field is missing!')
                }

                if (this.start_time === '') {
                    this.errors.push('The start time field is missing!')
                }

                if (this.end_time === '') {
                    this.errors.push('The end time field is missing!')
                }


                if(this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(AddEventApp).mount('#add-event-app');
</script>
{% endblock %}

apps/dashboard/templates/dashboard/apply_for_event.html
{% extends 'core/base.html' %} 

{% block content %} 
    <h1 class="title"> Apply for Event - {{ event.title }}</h1>

    <form method="post" action=".">

        {% csrf_token %}

        {% if form.errors %} 
            {% for error in form.errors %} 
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
        
        <div class="field">
            <lable>Content</lable>
            
            <div class="control">
                <textarea class="textarea" name="content" id="id_content"></textarea>
            </div>
        </div>

        <div class="field">
            <lable>Experience</lable>
            
            <div class="control">
                <textarea class="textarea" name="experience" id="id_experience"></textarea>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>

    </form>

 

{% endblock %} 

apps/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <h1 class="title">Dashboard</h1>

    <h2 class="subtitle has-text-centered">Newest Events</h2>
    {% for event in events %}
    <div class="columns">
        
            <div class="column is-12">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">{{ event.title }}</p>
                                <p class="subtitle is-6">{{ event.created_at }}</p>
                            </div>
                        </div>
                        
                        <div class="content">
                           <p>Short Description : {{ event.short_description }}</p>
                           <p>Long Description   : {{ event.long_description }}</p>
                           <p>Start Time         : {{ event.start_time }}</p>
                           <p>End Time           : {{ event.end_time }}</p>
                           <p>Volunteer Area     : {{ event.volunteer_area }}</p>

                            <hr>

                            <a href="{% url 'event_detail' event.id %} " class="button is-success">View</a>
                        </div>
                    </div>
                </div>
            </div>
            <br/><br/>
       
    </div>
    {% endfor %}
</div>
<style>
    .card-content{
        background: linear-gradient(45deg,#bda5ff,#6ac1c5);
    }
</style>
{% endblock %}
    
        

                

apps/dashboard/templates/dashboard/edit_event.html
{% extends 'core/base.html' %} 

{% block content %} 
    <div id="edit-event-app">
    <h1 class="title"> Edit Event</h1>

    <form v-on:submit="validateForm()" method="post" action="." >

        {% csrf_token %}

        {% if form.errors %} 
            {% for error in form.errors %} 
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="notifiation is-danger" v-if="errors.length">
            <p v-for="error in errors">
                [[ error ]]
            </p>

        </div>

        <div class="field">
            <lable> Title </lable>
            
            <div class="control">
                <input class="input" type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>
        
        <div class="field">
            <lable>Short description</lable>
            
            <div class="control">
                <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description"></textarea>
            </div>
        </div>

        <div class="field">
            <lable>Long description</lable>
            
            <div class="control">
                <textarea class="textarea" name="long_description" id="id_long_description">{% if event.long_description %}{{ event.long_description }}{% endif %}</textarea>
            </div>
        </div>

        <div class="field">
            <lable>Start Time</lable>
            
            <div class="control">
                <input type="datetime" name="start_time" id="id_start_time">{% if event.start_time %}{{ event.start_time }}{% endif %}</textarea>
            </div>
        </div>

        <div class="field">
            <lable>End Time</lable>
            
            <div class="control">
                <input type="datetime" name="end_time" id="id_end_time">{% if event.end_time %}{{ event.end_time }}{% endif %}</textarea>
            </div>
        </div>

        <div class="field">
            <lable> Volunteer Area </lable>
            
            <div class="control">
                <input class="input" type="text" name="volunteer_area" id="id_volunteer_area">{% if event.end_time %}{{ event.end_time }}{% endif %}
            </div>
        </div>
        

        <div class="field">
            <label>Status</label>

            <div class="control">
                <div class="select">
                    <select name="status">
                        <option value="active"{% if event.status == 'active' %} selected{% endif %}>Active</option>
                        <option value="booked"{% if event.status == 'booked' %} selected{% endif %}>Booked</option>
                        <option value="archived"{% if event.status == 'archived' %} selected{% endif %}>Archived</option>
                    </select>
                </div>
            </div>
        </div>

        


        <div class="field">
            <div class="control">
                <button class="button is-success">Save changes</button>
            </div>
        </div>

    </form>

</div>

 

{% endblock %} 

{% block scripts %}
<script>
    const EditEventApp = {
        data() {
            return {
                title: '{{ event.title }}',
                short_description: '{{ event.short_description }}',
                long_description: '{{ event.long_description }}',
                start_time: '{{ event.start_time }}',
                end_time: '{{ event.end_time }}',

                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = [] 

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                
                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                
                if (this.long_description === '') {
                    this.errors.push('The long description field is missing!')
                }
                
                if (this.start_time === '') {
                    this.errors.push('The start time field is missing!')
                }

                if (this.end_time === '') {
                    this.errors.push('The end time field is missing!')
                }


                if(this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(EditEventApp).mount('#edit-event-app');
</script>
{% endblock %}

apps/dashboard/templates/dashboard/event_detail.html
{% extends 'core/base.html' %} 

{% block content %} 
    <h1 class="title">{{ event.title }} ({{ event.get_status_display }})</h1>

    <p class="is-size-4"> {{ event.short_description }}</p>

    <p>Long Description   : {{ event.long_description }}</p>
    <p>Start Time         : {{ event.start_time }}</p>
    <p>End Time           : {{ event.end_time }}</p>
    <p>Volunteer Area     : {{ event.volunteer_area }}</p>

    <hr>


    {% if event.status == 'active' %} 
        <a href="{% url 'apply_for_event' event.id %}" class="button is-success">Apply for event</a>
    {% else %}
        <p> This event is not available anymore!!! </p>
    {% endif %}

{% endblock %} 

apps/dashboard/templates/dashboard/search.html
{% extends 'core/base.html' %} 

{% block content %} 
    <div id="search-app">
        <h1 class="title">Search</h1>

        <form @submit.prevent="performSearch()">
            <div class="columns">
                <div class="column is-4">
                    <div class="field">
                        

                        <div class="control">
                            <input class="input is-info" type="text" placeholder="Search For Events">
                           <!-- <input type="text" name="query" class="input" v-model="query"> -->
                        </div>
                    </div>
                

                    <div class="field">
                       <div class="control">
                            <button class="button is-success">Search</button>
                        </div>
                    </div>
                </div>
            </div> 
        </form>

        <div v-if="events.length">
            <hr>

            <div
                v-for="event in events"
                :key="event.id"
                class="notification mt-2"
            >
                <h3 class="is-size-4">[[ event.title ]]</h3>
                <p>[[ event.short_description ]]</p>
                <p>Start Time: [[ event.start_time ]]</p>

                <a :href="event.url">View details</a>
            </div>
        </div>
    </div>

    <style>
        .v-for{
        background: linear-gradient(45deg,#bda5ff,#6ac1c5);
        }
    </style>
{% endblock %}


{% block scripts %}
<script>
    const SearchApp = {
        data() {
            return {
                query: '',
                events: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            performSearch() {
                var data = {
                    'query': this.query
                }
                
                fetch('/events/api/search/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify(data)
                })
                .then((response) => {
                    return response.json()
                })
                .then((result) => {
                    console.log(result.events)
                    this.events = result.events
                })
                .catch((error) => {
                    console.log('Error', error)
                })

            }
        }
    }

    Vue.createApp(SearchApp).mount('#search-app')
</script>
{% endblock %} 