abvis/urls.py
from django.conf.urls import url
from apps.dashboard.views import  event_csv, event_pdf
from apps.notification.views import notifications
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include


from apps.core.views import frontpage, signup


urlpatterns = [
    path('', frontpage, name='frontpage'),
   
    path('event_csv', event_csv, name='event_csv'),
    path('event_pdf', event_pdf, name='event_pdf'),
    path('app/', include('apps.dashboard.urls')),
    path('signup/', signup, name='signup'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('admindashboard/', include('apps.userprofile.urls')),
    path('notifications/', include('apps.notification.urls')),
    path('events/', include('apps.dashboard.urls')),
    path('', include('apps.core.urls')),
    path('family/',include('apps.userprofile.urls')),
    path('area/',include('apps.userprofile.urls')),
    path('event/',include('apps.userprofile.urls')),
    
]

apps/core/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'core'
urlpatterns = [
    path('',views.frontpage, name='frontpage'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
] 

apps/core/models.py
from django.db import models
from django.urls import reverse

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=200, default='test')
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('core:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

apps/core/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from django.forms import ModelForm, DateInput
from .models import Event

class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
    
    def __init__(self, *args, **kwargs): 
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

apps/core/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login 
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm

from apps.dashboard.models import Event
from apps.userprofile.models import Userprofile

from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm



class CalendarView(generic.ListView):
    model = Event
    template_name = 'core/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        core = Calendar(d.year, d.month)
        html_cal = core.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('core:calendar'))
    return render(request, 'core/event.html', {'form': form})



def frontpage(request):
   return render(request, 'core/frontpage.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()

            account_type = request.POST.get('account_type','volunteer')

            if account_type == 'admin':
                userprofile = Userprofile.objects.create(user=user, is_admin=True)
                userprofile.save()
            else:
                userprofile = Userprofile.objects.create(user=user)
                userprofile.save()
                
            login(request, user)

            return redirect('admindashboard')
    else:
        form = SignUpForm()
    
    return render(request, 'core/signup.html', {'form': form})
    

apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" href="{% static 'core/images/style.css' %}">
<html>
    <head>
        <!-- Meta -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Title -->
        <title>XVISYS</title>
        <!-- Style -->
        
        
    
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">  
        
    </head>


    <body >
        <!-- Navbar -->
        
        <nav class="navbar is-info">
            <div class="navbar-brand">
                {% if request.user.is_authenticated %}
                    <a class="navbar-item" href="{% url 'dashboard' %}"><img src = "{% static 'core/images/Untitled1.png' %}"  alt="site logo" style="max-height: 70px" class="py-2 px-2"></a> 
                {% else %}
                <a class="navbar-item" href="{% url 'frontpage' %}"><img src = "{% static 'core/images/Untitled1.png' %}"  alt="site logo" style="max-height: 70px" class="py-2 px-2"></a>
                {% endif %}
            </div>
            
            

            <div class="navbar-menu">
                <div class="navbar-end">
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link" href="#">
                          Download
                        </a>
                        <div class="navbar-dropdown is-boxed">
                          <a class="navbar-item" href="{% url 'event_pdf' %}">
                            Event PDF File
                          </a>
                          <a class="navbar-item" href="{% url 'event_csv' %}">
                            Event CSV File
                          </a>
                        </div>
                    </div>

                    
                    <a href="{% url 'core:calendar'  %}" class="navbar-item">Calendar</a>
                    <a href="{% url 'search' %}" class="navbar-item">Search</a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'admindashboard'  %}" class="navbar-item">Dashboard</a>
                        <a href="{% url 'notifications' %}" class="navbar-item">Notifications ({{ notifications.count }})</a>
                    {% endif %}
                    <div class="navbar-item">
                        <div class="buttons">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'logout' %}" class="button is-danger">Log out</a>

                            {% else %}
                                <a href="{% url 'signup' %}" class="button is-primary"><strong>Sign up</strong></a>
                                <a href="{% url 'login' %}" class="button is-light">Log in</a>
                            {% endif %}
                        </div>
                     </div>
                 </div>
            </div>
        </nav>
  <!-- End Navbar-->
<br>
<br>
<br>
<br>
        
     <!--Main content -->

<section class="section" >
        {% block content %}
        {% endblock %}
        
</section>
    

    <!-- End Main Content -->

    <!-- Scripts -->

<script src="https://unpkg.com/vue@next"></script>

    
    {% block scripts %}
    {% endblock %}

   

<style scoped>
       .navbar {
        position:fixed;
        width: 100%;
        height: 85px;

       }
</style>




    



  </body>
  <style scoped>
    body {
  background: linear-gradient(45deg,#6ac1c5, #bda5ff);
  min-height: 100%;
}
</style>

</html>

apps/core/templates/core/basic.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>
  
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
 
<style>
  body{
    background : linear-gradient(45deg,#bda5ff,#6ac1c5); 
    height: 100%;
  }
  html{
    height:100%;
  }
</style>

</html>

apps/core/templates/core/calendar.html
{% extends 'core/basic.html' %}


{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'core:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-success left" href="{% url 'dashboard' %}?{{ next_month }}"> Back to Frontpage </a>
	<a class="btn btn-info right" href="{% url 'core:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'core:event_new' %}"> Add Event </a>
</div>
 

{{ calendar }}


{% endblock %}

apps/core/templates/core/event.html
{% extends 'core/basic.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'core:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

apps/core/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}


<link rel="stylesheet" href="{% static 'core/images/style.css' %}">

<!--<figure class="image is-128x128"> 
    <img src="{% static 'core/images/images4.jpg' %}"  >
</figure>
-->


<body id="bg" style="background-image: url('{% static 'core/images/team.jpeg'%}');">


 

    
    <div class="box" id='box' style="background-image: url('{% static 'core/images/image.jpeg'%}');">
        <h1 class="title ">Welcome to Xvisys</h1>
        <h4 class="subtitle has-text-dark">A Volunteer Management System For Public Charter Schools</h4>
    </div>

</body>

<!-- 

<header class="header header-inverse h-fullscreen pb-80" style="background-color: #31b8f5">
    <div class="container has-text-centered">
        <div class="row h-full">
            <div class="container">
                <h1 class="title"><strong>Welcome to Xvisys</strong> </h1>
                <h2 class="subtitle"> A Volunteer Tracker</h2>
            </div>
        </div>
    </div>

<div class="twp-video-background">
    <div class="twp-video-foreground">
        <iframe width="1160" height="655"  src="https://www.youtube.com/embed/zaPo86cfmDQ?controls=0&showinfo=0&rel=0&autoplay=1&loop=1&playlist=zaPo86cfmDQ&mute=1" title="YouTube video player" frameborder="0" allowfullscreen allow="autoplay"></iframe>
    </div>
    <div class="twp-video-layer"></div>
</div>

    
</header>
    



<section class="hero is-small is-primary is-light">
    
    <div class="hero-body">
    <div class="twp-video-background">
        <div class="twp-video-foreground">
            <iframe width="1120" height="350"  src="https://www.youtube.com/embed/zaPo86cfmDQ?controls=0&showinfo=0&rel=0&autoplay=1&loop=1&playlist=zaPo86cfmDQ&mute=1" title="YouTube video player" frameborder="0" allowfullscreen allow="autoplay"></iframe>
        </div>
        <div class="twp-video-layer"></div>
    </div>
</section>


        
<footer class="sticky-footer">
    <div class="content has-text-centered">
        <p><strong>Xvisys</strong> by Abhishek and Binayak</p>
        Copyright (c) 2021
    </div>
</footer>
-->


{% endblock %}

apps/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<div class="container">
    <div class="column">
        <div class="column is-6 is-offset-3">
            <h1 class="title">Log in</h1>

            <form method="post" action=".">
                {% csrf_token %}

                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Username">
                  </div>
                  <br>
                  <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Password">
                  </div>
                    

                <br>

            <p>Don't have an account ? Create one <a href="/signup">here</a></p>

            <br>

            <div class="feild">
                <div class="control">
                    <button class="button is-primary" type="submit">Log in</button>
                </div>
             </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/core/templates/core/signup.html
{% extends 'core/base.html' %}



{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<div class="shadow p-4 mb-5 bg-body rounded">
    <div class="container">
        <div class="column">
            <div class="column is-6 is-offset-3">
                
                <h1 class="title">Sign up</h1>

                
                    <form method="post" action=".">

                        {% csrf_token %}

                        {{ form.as_p }} 

                        <br>

                        <div class="field">
                            <label>Account type</label>
                            

                            <br>
                            <div class="control">
                                <div class="select">
                                    <select name="account_type">
                                        <option value="volunteer" selected>Volunteer</option>
                                        <option value="admin">Admin</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        
                        <div class="feild">
                            <div class="control">
                                <button class="button is-primary" type="submit">Sign up</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

   
</div>
<style>
    .container {
     
    background: linear-gradient(45deg,#6ac1c5, #bda5ff);

    }

    .shadow {
        background: linear-gradient(45deg,#6ac1c5, #bda5ff);
    }
     

</style>
{% endblock %}